### PR TITLE
Update jobs.txt - Adds reputation gain to all jobs

### PR DESCRIPTION
**Pull request by AlexBassett**

### CODE REVIEW

**Comment by Lorantine** [comment]
Future tip: X += 1 can be simplified to X++
Both mean the same: X = (X + 1)
For X += 2 and so forth keep it as is (+=).

Same works for negative:
X -= 1 can be simplified to X-- while X -= 2 should stay as is (-=).

Functionally it's the same though, so doesn't matter, and the change looks fine to me.

**Comment by AlexBassett** [comment]
I went with += cuz I was overhauling all of them and I wanted a template where I could just copy paste it in and add a numerical value

**Comment by Lorantine** [comment]
+= 1 is the same as ++ anyway, and seeing the number after does look nicer, so I'm not against it.

**Comment by kikotheexile** [comment]
The diff looks good to me, even if the template isn't exact, it does what we need it to and not inefficiently. (Honestly it looks better than ++ anyway, easier for new people to read)

On the spot merging. Thank you!

**Pull request merged**
