### PR TITLE
Bugfix for trust fund kid start

### PR DESCRIPTION
**Pull request by Philemon121**
More bugfixes, this time for the easy mode. The mission that drops 250000 credits on the player now triggers properly.

### CODE REVIEW

**Comment by kikotheexile** [comment]
the diff shows that every single line of this file is different, can you double check the intro and make sure it all still works? *(even if just one james branch works, that should prove all three do)*

**Comment by kikotheexile** [comment]
> Philemon120Today at 9:43 AM
`Oh
just went through it myself, there's my changes and then a shit ton of line differences (all that seems to have actually changed is a bunch of extra blank lines)
imma turn off a script in NP++`
> Kiko the ExileToday at 9:45 AM
`i dont care if theres extra lines/whitespace/blanks if the missions work
optimization matters, but it doesn't matter that much`
> Philemon120Today at 9:46 AM
`They annoy me so imma clean up anyway by putting the fixed mission in a fresh version of the file over where the original mission is`

**Comment by Philemon121** [comment]
The cleanup didn't actually work, but I went through and confirmed all the missions still work.

**Comment by kikotheexile** [comment]
Thank you. Merging.

**Pull request merged**
