### PR TITLE
RNS Fixes 2

### PR DESCRIPTION
**Pull request by Philemon121**
Electric Filetype Error

Just like last time, mostly typos and backticks, with a couple small wording changes and the death of many colons.

### CODE REVIEW

**Comment by Lorantine** [comment]
When I paste your changed version into my NotePad++, the only 2 things I see changed are:
- The new commit, 53abea1, is removed.
- Empty lines have their whitespace removed (which doesn't matter much).

Apart from that, I don't see any changes?

Additionally: "and the death of many colons"?
I know this since I was the one that added the colons in #41 : The colons are correct grammar-wise, which is why I added them. Colons before quotes are very common (the other being a comma, and which of the two depends on some rules). Do NOT remove those colons, unless you are certain they are incorrect in whatever case they're used in.
If you believe any colons to be incorrect, find a reliable source online backing your claim up. If your reason for removing colons was basically "I don't know why they're there, I'll just remove them", don't do that, please.

**Comment by Lorantine** [comment]
Side note, your PR is conflicted, meaning it can't be merged unless it's resolved. I saw you had some trouble making a PR, so you can ask on the Discord how to fix this.

**Comment by kikotheexile** [comment]
I'm not able to merge this as is due to conflicts, but i could do a cut-paste of the text into the file and make the additions there. 

Additionally, the concerns of the differences in grammatical style need resolved, and as I am not a writer, it is not for me to decide what is the more grammatically correct or better looking of the two.

**Comment by Philemon121** [comment]
For whatever reason (probably a crash), the RNS changes vanished, and I forgot to check the diff because I had finished making those changes 15 minutes before. As for the colons, I don't have time at the moment to look into them, but I will later (I removed them because they looked strange and off memory it didn't seem right). I'll remake the changes and figure out the conflict sometime this afternoon.

**Comment by kikotheexile** [comment]
For the time being I will close this pr then. It probably shouldn't sit in queue.

**Pull request closed without merging**
