### PR TITLE
Quotation Fixes

### PR DESCRIPTION
**Pull request by JPG7D**
Fixed errors where closing quotations were not present.

### CODE REVIEW

**Review by lukearndt — CHANGES_REQUESTED** [review]
This does a lot more than it claims to. It would be great to have a version that only fixes quotation marks.

**Comment by JPG7D** [comment]
> This does a lot more than it claims to. It would be great to have a version that only fixes quotation marks.

While I was fixing the quotations, I had been using an outdated version of Endless Sky Civil War. The current version does have all the changes made aside from the quotation fixes.

**Comment by lukearndt** [comment]
Yep, I get where you're coming from. The problem is that if we merge this as it currently stands, it'll make a lot of other changes to the files aren't what you're trying to do. Those unintended changes would probably break a lot of things.

**Comment by JPG7D** [comment]
I'll create a pull request after I merge the main branch onto my fork.

**Pull request closed without merging**
