### PR TITLE
Port formation-flying to ESCW / ES-Stories

### PR DESCRIPTION
**Pull request by petervdmeer**
**Feature:** This PR implements (ports) formation flying from ES

## Feature Details
Port of formation flying from https://github.com/endless-sky/endless-sky/pull/4471
See the PR at endless-sky for details.

## UI Screenshots
Here is a screenshot of a formation in ESCW/ES-Stories:
ESCW_formation

## Usage Examples
See the PR at endless-sky for controls (shift-F, shift-G, shift-H) and other details.

### CODE REVIEW

**Comment by kikotheexile** [comment]
I do need to know the basics of how i could use this in NPC fleets so that I can make sure this actually gets used/implemented.

**Comment by tehhowch** [comment]
Part of the reason for the RFC I suggested be written and collaboratively reviewed was so that people could decide on the syntax and behavior that makes sense. Instead the response on the RFC was "hey cool I want it; I didn't look at the code"

As folks here experiment with using the syntax, please provide useful feedback on the RFC so we can move it forward.

https://github.com/EndlessSkyCommunity/endless-sky/pull/52

**Comment by petervdmeer** [comment]
> I do need to know the basics of how i could use this in NPC fleets so that I can make sure this actually gets used/implemented.

If you just want to try formations in the game, then get yourself a couple of ships and just press shift-G to change formations. (And press shift-F and shift-H for changing the ring.)

If you want to use this for NPCs, then you can add a formation directly at a fleet. Here is the example from the ES-PR:
```
fleet
	names "civilian"
	formation "Delta (tailing)"
	variant
		"Flivver (Racing)" 10
```
Formations currently work best for NPCs that escort the player. Formations are formed while ships are idle and non-escorting NPCs don't have a lot of idle time at the moment.

**Comment by kikotheexile** [comment]
> Part of the reason for the RFC I suggested be written and collaboratively reviewed was so that people could decide on the syntax and behavior that makes sense. Instead the response on the RFC was "hey cool I want it; I didn't look at the code"
> 
> As folks here experiment with using the syntax, please provide useful feedback on the RFC so we can move it forward.
> 
> [EndlessSkyCommunity/endless-sky#52](https://github.com/EndlessSkyCommunity/endless-sky/pull/52)

All of my knowledge of c++ comes from reverse enginering world of warcraft about 10 years ago. So i only have a cursory understanding of proper code, and am very bad at it. The best i can really do is check for conflicts, so i won't be useful to the RFC for the reason you implemented it. I am sorry about that.

**Comment by kikotheexile** [comment]
> > I do need to know the basics of how i could use this in NPC fleets so that I can make sure this actually gets used/implemented.
> 
> If you just want to try formations in the game, then get yourself a couple of ships and just press shift-G to change formations. (And press shift-F and shift-H for changing the ring.)
> 
> If you want to use this for NPCs, then you can add a formation directly at a fleet. Here is the example from the ES-PR:
> 
> ```
> fleet
> 	names "civilian"
> 	formation "Delta (tailing)"
> 	variant
> 		"Flivver (Racing)" 10
> ```
> 
> Formations currently work best for NPCs that escort the player. Formations are formed while ships are idle and non-escorting NPCs don't have a lot of idle time at the moment.

Thank you, this provides a quick reference that i can direct people to look at.

**Comment by tehhowch** [comment]
> 
> 
> > Part of the reason for the RFC I suggested be written and collaboratively reviewed was so that people could decide on the syntax and behavior that makes sense. Instead the response on the RFC was "hey cool I want it; I didn't look at the code"
> > As folks here experiment with using the syntax, please provide useful feedback on the RFC so we can move it forward.
> > [EndlessSkyCommunity/endless-sky#52](https://github.com/EndlessSkyCommunity/endless-sky/pull/52)
> 
> All of my knowledge of c++ comes from reverse enginering world of warcraft about 10 years ago. So i only have a cursory understanding of proper code, and am very bad at it. The best i can really do is check for conflicts, so i won't be useful to the RFC for the reason you implemented it. I am sorry about that.

The RFC contains *zero* C++. The point of the RFC is to define how people use the functionality, i.e. what the plain-text syntax is, and what behavior those data file keywords translate into. That's why I requested review from content creators, i.e. the people that would be using the feature.

**Comment by kikotheexile** [comment]
Your frustration is understandable, I just need a cheat sheet for content implementation. If you want to discuss this further im more than happy to via discord.

**Pull request merged**
